- name: version
  run: echo "::set-output name=version::$(npm pkg get version | sed 's/"//g')"
  id: version
- name: release
  uses: actions/create-release@v1
  id: create_release
  with:
    draft: false
    prerelease: false
    release_name: ${{ steps.version.outputs.version }}
    tag_name: ${{ github.ref }}
    body_path: CHANGELOG.md
  env:
    GITHUB_TOKEN: ${{ github.token }}
- name: build artifacts
  run: npm run build
- name: upload linux artifact
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ github.token }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: ./build.tar.gz
    asset_name: build.tar.gz
    asset_content_type: application/gzip
- name: upload windows artifact
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ github.token }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: ./build.zip
    asset_name: build.zip
    asset_content_type: application/zip